#!/usr/bin/env php
<?php
/**
 * Console run file
 * @var \Composer\Autoload\ClassLoader $composer
 */
$composer = require(__DIR__ . '/vendor/autoload.php');
$configsPath = dirname(__FILE__) . DIRECTORY_SEPARATOR . 'Config';
$appType = \Reaction\StaticApplicationInterface::APP_TYPE_CONSOLE;

Reaction::init($composer, $configsPath, $appType);

Reaction::$app->run();